### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ofpiyush** [nnupoor/pathly#1]
```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/piyush/[redacted]/node_modules/pathly/dist/main.js:1:274)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/piyush/[redacted]/index.js:2:14)
    at Module._compile (module.js:635:30)
```

**Comment by nnupoor-zz** [comment]
Caused by using --save-dev while installing. Fixed README.md

**Comment by ofpiyush** [comment]
Nope, this is caused by having no `window` object on the server side.

**Comment by nnupoor-zz** [comment]
My bad. First module out in the open 😄 I haven't used window object anywhere, seems like Babel introduced it. Pushing a fix.

**Comment by nnupoor-zz** [comment]
I have fixed it. Webpack target was wrong(web). Let me know if it works for you, and I'll close the issue else work on fixing it. Thanks for taking out the time @ofpiyush  :)

**Comment by ofpiyush** [comment]
```
=====path undefined====== Error: The path entered is incorrect
    at e.exports (/Users/piyush/[redacted]/node_modules/pathly/dist/main.js:1:1003)
    at Object.<anonymous> (/Users/piyush/[redacted]/index.js:20:44)
    at Module._compile (module.js:635:30)
    at loader (/Users/piyush/[redacted]/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/piyush/[redacted]/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at Object.<anonymous> (/Users/piyush/[redacted]/node_modules/babel-cli/lib/_babel-node.js:154:22)
```

I am not sure if this is something I've done. I assume it should return `null` ?

**Comment by nnupoor-zz** [comment]
Weird, I installed it in a project, with npm i, and ran it inside a simple node app.js file and it works for me. Can you tell me the steps you used?

**Comment by ofpiyush** [comment]
Ref: https://gist.github.com/ofpiyush/7ec518f5ee4344335c3942680fb0efdb

**Comment by nnupoor-zz** [comment]
@ofpiyush Updated the code, to return null instead of throwing an Error for invalid params. 
Now, you should get logs as:
`=====path undefined====== null
The path entered is incorrect
`
Also shortened the chained functions! 🍺

**Comment by ofpiyush** [comment]
I also get
```
=====curryd====== [ { title: 'Hello World!',
    authors: [ 'Jason fried', 'Paul Kinlan' ] },
  { title: 'JS For Beginners', authors: [ 'Yehuda Katz' ] },
  { title: 'Node For Beginners', authors: [] },
  { title: 'Software Development',
    authors: [ 'Martin Fowler', 'Donald Knuth', 'Linus Torvalds' ] } ]
The path entered is incorrect
```
Is this expected?

**Comment by nnupoor-zz** [comment]
@ofpiyush `The path entered is incorrect` is for next functions, with undefined param
![screen shot 2018-04-02 at 3 20 39 pm](https://user-images.githubusercontent.com/4323265/38192208-7454fbdc-3689-11e8-9662-e45e925a3bc3.png)

In the browser, if you check the trace of warning, it shows the callee. The warning msg is shown first and then null is returned hence the behavior. 

The examples do need a better formatting though.

**Comment by ofpiyush** [comment]
You're right! It's for the next one. Cheers karo! 🍸
